-- Yokan
-- Standalone colorscheme (no external dependencies)
-- Originally based on zenbones + lush; baked into static highlight calls.

vim.g.colors_name = "Yokan"

local bg = vim.o.background

if bg == "light" then
  vim.api.nvim_set_hl(0, '@attribute', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@attribute.builtin', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@boolean', {fg='#28403e', italic=true})
  vim.api.nvim_set_hl(0, '@character', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@character.special', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@comment', {fg='#919191', italic=true})
  vim.api.nvim_set_hl(0, '@comment.documentation', {fg='#919191', italic=true})
  vim.api.nvim_set_hl(0, '@comment.error', {fg='#895883'})
  vim.api.nvim_set_hl(0, '@comment.note', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@comment.todo', {bold=true, underline=true})
  vim.api.nvim_set_hl(0, '@comment.warning', {fg='#53372a'})
  vim.api.nvim_set_hl(0, '@constant', {fg='#3a5b58', bold=true})
  vim.api.nvim_set_hl(0, '@constant.builtin', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@constant.macro', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@constructor', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@constructor.lua', {fg='#868686'})
  vim.api.nvim_set_hl(0, '@diff.delta', {bg='#c1eae7'})
  vim.api.nvim_set_hl(0, '@diff.minus', {bg='#eedeec'})
  vim.api.nvim_set_hl(0, '@diff.plus', {bg='#ece2be'})
  vim.api.nvim_set_hl(0, '@function', {fg='#28403e'})
  vim.api.nvim_set_hl(0, '@function.builtin', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@function.call', {fg='#28403e'})
  vim.api.nvim_set_hl(0, '@function.macro', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@function.method', {fg='#28403e'})
  vim.api.nvim_set_hl(0, '@function.method.call', {fg='#28403e'})
  vim.api.nvim_set_hl(0, '@keyword', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.conditional', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.conditional.ternary', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.coroutine', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.debug', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@keyword.directive', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.directive.define', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.exception', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.function', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.import', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.operator', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.repeat', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.return', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.storage', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@label', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@label.vimdoc', {fg='#735057', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.mod.deprecated', {fg='#53372a'})
  vim.api.nvim_set_hl(0, '@lsp.type.boolean', {fg='#28403e', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.builtinType', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.class', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.comment', {fg='#919191', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.decorator', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.type.deriveHelper', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.type.enum', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.enumMember', {fg='#3a5b58', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.type.escapeSequence', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@lsp.type.event', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.formatSpecifier', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@lsp.type.function', {fg='#28403e'})
  vim.api.nvim_set_hl(0, '@lsp.type.generic', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, '@lsp.type.interface', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.keyword', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.type.lifetime', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.macro', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.method', {fg='#28403e'})
  vim.api.nvim_set_hl(0, '@lsp.type.modifier', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.namespace', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.number', {fg='#486f6c'})
  vim.api.nvim_set_hl(0, '@lsp.type.operator', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.type.parameter', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, '@lsp.type.property', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, '@lsp.type.regexp', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.selfKeyword', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.selfTypeKeyword', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.string', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.struct', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.type', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.typeAlias', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.typeParameter', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.unresolvedReference', {sp='#895883', undercurl=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.class.defaultLibrary', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.enum.defaultLibrary', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.enumMember.defaultLibrary', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.function.defaultLibrary', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@lsp.typemod.keyword.async', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.keyword.injected', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.macro.defaultLibrary', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@lsp.typemod.method.defaultLibrary', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@lsp.typemod.operator.injected', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.string.injected', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.struct.defaultLibrary', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.type.defaultLibrary', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.typeAlias.defaultLibrary', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.variable.callable', {fg='#28403e'})
  vim.api.nvim_set_hl(0, '@lsp.typemod.variable.defaultLibrary', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.variable.injected', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, '@lsp.typemod.variable.static', {fg='#3a5b58', bold=true})
  vim.api.nvim_set_hl(0, '@markup', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@markup.environment', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@markup.heading', {fg='#28403e', bold=true})
  vim.api.nvim_set_hl(0, '@markup.heading.1.delimiter.vimdoc', {fg='#f3f3f3', bg='#f3f3f3', sp='#28403e'})
  vim.api.nvim_set_hl(0, '@markup.heading.2.delimiter.vimdoc', {fg='#f3f3f3', bg='#f3f3f3', sp='#28403e', underline=true})
  vim.api.nvim_set_hl(0, '@markup.italic', {italic=true})
  vim.api.nvim_set_hl(0, '@markup.italic.markdown', {italic=true})
  vim.api.nvim_set_hl(0, '@markup.link', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@markup.link.label', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@markup.link.markdown', {fg='#3a5b58', underline=true})
  vim.api.nvim_set_hl(0, '@markup.link.url', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@markup.link.url.markdown', {fg='#919191'})
  vim.api.nvim_set_hl(0, '@markup.link.vimdoc', {fg='#3a5b58', underline=true})
  vim.api.nvim_set_hl(0, '@markup.list', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@markup.list.checked', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@markup.list.unchecked', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@markup.math', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@markup.quote', {fg='#486f6c'})
  vim.api.nvim_set_hl(0, '@markup.raw', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@markup.raw.block', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@markup.raw.markdown', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@markup.strikethrough', {strikethrough=true})
  vim.api.nvim_set_hl(0, '@markup.strong', {bold=true})
  vim.api.nvim_set_hl(0, '@markup.title.markdown', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@markup.underline', {underline=true})
  vim.api.nvim_set_hl(0, '@module', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@module.builtin', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@number', {fg='#486f6c'})
  vim.api.nvim_set_hl(0, '@number.float', {fg='#486f6c'})
  vim.api.nvim_set_hl(0, '@operator', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, '@property', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, '@punctuation', {fg='#868686'})
  vim.api.nvim_set_hl(0, '@punctuation.bracket', {fg='#868686'})
  vim.api.nvim_set_hl(0, '@punctuation.delimiter', {fg='#868686'})
  vim.api.nvim_set_hl(0, '@punctuation.special', {fg='#868686'})
  vim.api.nvim_set_hl(0, '@punctuation.special.markdown', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@string', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@string.documentation', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@string.escape', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@string.escape.markdown', {fg='#b0b0b0', italic=true})
  vim.api.nvim_set_hl(0, '@string.regexp', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@string.special', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@string.special.path', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@string.special.symbol', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, '@string.special.url', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@tag', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@tag.attribute', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, '@tag.builtin', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@tag.delimiter', {fg='#868686'})
  vim.api.nvim_set_hl(0, '@type', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@type.builtin', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@type.definition', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@type.qualifier', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, '@variable', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, '@variable.builtin', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, '@variable.member', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, '@variable.parameter', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, '@variable.parameter.builtin', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, '@variable.parameter.vimdoc', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, 'Added', {fg='#005523'})
  vim.api.nvim_set_hl(0, 'BlinkCmpKind', {fg='#486f6c'})
  vim.api.nvim_set_hl(0, 'BlinkCmpLabelDescription', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, 'BlinkCmpLabelDetail', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, 'BlinkCmpSource', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, 'Bold', {bold=true})
  vim.api.nvim_set_hl(0, 'Boolean', {fg='#28403e', italic=true})
  vim.api.nvim_set_hl(0, 'BufferCurrent', {bold=true})
  vim.api.nvim_set_hl(0, 'BufferVisible', {fg='#4c7471'})
  vim.api.nvim_set_hl(0, 'BufferVisibleIndex', {fg='#4c7471'})
  vim.api.nvim_set_hl(0, 'BufferVisibleSign', {fg='#4c7471'})
  vim.api.nvim_set_hl(0, 'Changed', {fg='#007373'})
  vim.api.nvim_set_hl(0, 'Character', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'CmpItemAbbr', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, 'CmpItemAbbrDeprecated', {fg='#60928e'})
  vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch', {fg='#28403e', bold=true})
  vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzy', {fg='#355350', bold=true})
  vim.api.nvim_set_hl(0, 'CmpItemKind', {fg='#486f6c'})
  vim.api.nvim_set_hl(0, 'CmpItemMenu', {fg='#507a76'})
  vim.api.nvim_set_hl(0, 'CocCodeLens', {fg='#9b9b9b'})
  vim.api.nvim_set_hl(0, 'CocErrorHighlight', {sp='#895883', undercurl=true})
  vim.api.nvim_set_hl(0, 'CocErrorSign', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'CocErrorVirtualText', {fg='#895883', bg='#f2e4f0'})
  vim.api.nvim_set_hl(0, 'CocHintHighlight', {sp='#a5679c', undercurl=true})
  vim.api.nvim_set_hl(0, 'CocHintSign', {fg='#a5679c'})
  vim.api.nvim_set_hl(0, 'CocInfoHighlight', {sp='#69a6a2', undercurl=true})
  vim.api.nvim_set_hl(0, 'CocInfoSign', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'CocMarkdownLink', {fg='#7bc3bd', underline=true})
  vim.api.nvim_set_hl(0, 'CocMenuSel', {bg='#ebebeb'})
  vim.api.nvim_set_hl(0, 'CocSearch', {fg='#28403e', bg='#dfc0da'})
  vim.api.nvim_set_hl(0, 'CocSelectedText', {fg='#7f5d7b', sp='#895883', undercurl=true})
  vim.api.nvim_set_hl(0, 'CocWarningHighlight', {sp='#53372a', undercurl=true})
  vim.api.nvim_set_hl(0, 'CocWarningSign', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'CocWarningVirtualText', {fg='#53372a', bg='#f2e6e1'})
  vim.api.nvim_set_hl(0, 'ColorColumn', {bg='#e8ccc1'})
  vim.api.nvim_set_hl(0, 'Comment', {fg='#919191', italic=true})
  vim.api.nvim_set_hl(0, 'ComplHint', {fg='#b0b0b0'})
  vim.api.nvim_set_hl(0, 'ComplHintMore', {fg='#807750', bold=true})
  vim.api.nvim_set_hl(0, 'Conceal', {fg='#507a76', bold=true, italic=true})
  vim.api.nvim_set_hl(0, 'Conditional', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, 'Constant', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'CurSearch', {fg='#f3f3f3', bg='#c07db6', bold=true})
  vim.api.nvim_set_hl(0, 'Cursor', {fg='#f3f3f3', bg='#28403e'})
  vim.api.nvim_set_hl(0, 'CursorColumn', {bg='#ebebeb'})
  vim.api.nvim_set_hl(0, 'CursorIM', {fg='#f3f3f3', bg='#28403e'})
  vim.api.nvim_set_hl(0, 'CursorLine', {bg='#ebebeb'})
  vim.api.nvim_set_hl(0, 'CursorLineFold', {fg='#9b9b9b', bold=true})
  vim.api.nvim_set_hl(0, 'CursorLineNr', {fg='#28403e', bold=true})
  vim.api.nvim_set_hl(0, 'CursorLineSign', {fg='#9b9b9b'})
  vim.api.nvim_set_hl(0, 'Debug', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'Define', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, 'Delimiter', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'DiagnosticDeprecated', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'DiagnosticError', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'DiagnosticFloatingError', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'DiagnosticFloatingHint', {fg='#a5679c'})
  vim.api.nvim_set_hl(0, 'DiagnosticFloatingInfo', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'DiagnosticFloatingOk', {fg='#807750'})
  vim.api.nvim_set_hl(0, 'DiagnosticFloatingWarn', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'DiagnosticHint', {fg='#a5679c'})
  vim.api.nvim_set_hl(0, 'DiagnosticInfo', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'DiagnosticOk', {fg='#807750'})
  vim.api.nvim_set_hl(0, 'DiagnosticSignError', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'DiagnosticSignHint', {fg='#a5679c'})
  vim.api.nvim_set_hl(0, 'DiagnosticSignInfo', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'DiagnosticSignOk', {fg='#807750'})
  vim.api.nvim_set_hl(0, 'DiagnosticSignWarn', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', {sp='#895883', undercurl=true})
  vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint', {sp='#a5679c', undercurl=true})
  vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo', {sp='#69a6a2', undercurl=true})
  vim.api.nvim_set_hl(0, 'DiagnosticUnderlineOk', {sp='#807750', undercurl=true})
  vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn', {sp='#53372a', undercurl=true})
  vim.api.nvim_set_hl(0, 'DiagnosticUnnecessary', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualLinesError', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualLinesHint', {fg='#a5679c'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualLinesInfo', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualLinesOk', {fg='#807750'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualLinesWarn', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextError', {fg='#895883', bg='#f2e4f0'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextHint', {fg='#a5679c', bg='#f2e4ef'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextInfo', {fg='#69a6a2', bg='#bff2ee'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextOk', {fg='#807750', bg='#f3e8c2'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextWarn', {fg='#53372a', bg='#f2e6e1'})
  vim.api.nvim_set_hl(0, 'DiagnosticWarn', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'DiffAdd', {bg='#ece2be'})
  vim.api.nvim_set_hl(0, 'DiffChange', {bg='#c1eae7'})
  vim.api.nvim_set_hl(0, 'DiffDelete', {bg='#eedeec'})
  vim.api.nvim_set_hl(0, 'DiffText', {fg='#28403e', bg='#a5c8c5'})
  vim.api.nvim_set_hl(0, 'DiffTextAdd', {fg='#28403e', bg='#a5c8c5'})
  vim.api.nvim_set_hl(0, 'Directory', {bold=true})
  vim.api.nvim_set_hl(0, 'EndOfBuffer', {fg='#b0b0b0'})
  vim.api.nvim_set_hl(0, 'Error', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'ErrorMsg', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'Exception', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, 'FlashBackdrop', {fg='#919191'})
  vim.api.nvim_set_hl(0, 'FlashLabel', {fg='#28403e', bg='#8ad7d2'})
  vim.api.nvim_set_hl(0, 'Float', {fg='#486f6c'})
  vim.api.nvim_set_hl(0, 'FloatBorder', {fg='#727272'})
  vim.api.nvim_set_hl(0, 'FloatFooter', {fg='#28403e', bg='#dddddd', bold=true})
  vim.api.nvim_set_hl(0, 'FloatShadow', {bg='#9b9ea4'})
  vim.api.nvim_set_hl(0, 'FloatShadowThrough', {bg='#9b9ea4'})
  vim.api.nvim_set_hl(0, 'FloatTitle', {fg='#28403e', bg='#dddddd', bold=true})
  vim.api.nvim_set_hl(0, 'FoldColumn', {fg='#9b9b9b', bold=true})
  vim.api.nvim_set_hl(0, 'Folded', {fg='#28403e'})
  vim.api.nvim_set_hl(0, 'Function', {fg='#28403e'})
  vim.api.nvim_set_hl(0, 'FzfLuaBufFlagAlt', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'FzfLuaBufFlagCur', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'FzfLuaBufName', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, 'FzfLuaBufNr', {fg='#807750'})
  vim.api.nvim_set_hl(0, 'FzfLuaFzfCursorLine', {bg='#ebebeb'})
  vim.api.nvim_set_hl(0, 'FzfLuaFzfMatch', {fg='#a5679c', bold=true})
  vim.api.nvim_set_hl(0, 'FzfLuaHeaderBind', {fg='#807750'})
  vim.api.nvim_set_hl(0, 'FzfLuaHeaderText', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'FzfLuaLiveSym', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'FzfLuaPathColNr', {fg='#735057', bold=true})
  vim.api.nvim_set_hl(0, 'FzfLuaPathLineNr', {fg='#735057', bold=true})
  vim.api.nvim_set_hl(0, 'FzfLuaTabMarker', {fg='#807750'})
  vim.api.nvim_set_hl(0, 'FzfLuaTabTitle', {fg='#7bc3bd'})
  vim.api.nvim_set_hl(0, 'FzfLuaTitle', {fg='#28403e', bold=true})
  vim.api.nvim_set_hl(0, 'GitGutterAdd', {fg='#807750'})
  vim.api.nvim_set_hl(0, 'GitGutterChange', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'GitGutterDelete', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'GitSignsAdd', {fg='#807750'})
  vim.api.nvim_set_hl(0, 'GitSignsChange', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'GitSignsDelete', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'HopNextKey', {fg='#a5679c', bold=true, underline=true})
  vim.api.nvim_set_hl(0, 'HopNextKey1', {fg='#7bc3bd', bold=true, underline=true})
  vim.api.nvim_set_hl(0, 'HopNextKey2', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'HopUnmatched', {fg='#919191'})
  vim.api.nvim_set_hl(0, 'IblIndent', {fg='#e2e2e2'})
  vim.api.nvim_set_hl(0, 'IblScope', {fg='#b9b9b9'})
  vim.api.nvim_set_hl(0, 'Identifier', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, 'Ignore', {fg='#28403e', bg='#f3f3f3'})
  vim.api.nvim_set_hl(0, 'IncSearch', {fg='#f3f3f3', bg='#c07db6', bold=true})
  vim.api.nvim_set_hl(0, 'Include', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, 'IndentLine', {fg='#e2e2e2'})
  vim.api.nvim_set_hl(0, 'IndentLineCurrent', {fg='#b9b9b9'})
  vim.api.nvim_set_hl(0, 'Italic', {italic=true})
  vim.api.nvim_set_hl(0, 'Keyword', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, 'Label', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, 'LineNr', {fg='#9b9b9b'})
  vim.api.nvim_set_hl(0, 'LineNrAbove', {fg='#9b9b9b'})
  vim.api.nvim_set_hl(0, 'LineNrBelow', {fg='#9b9b9b'})
  vim.api.nvim_set_hl(0, 'LspCodeLens', {fg='#9b9b9b'})
  vim.api.nvim_set_hl(0, 'LspCodeLensSeparator', {fg='#9b9b9b'})
  vim.api.nvim_set_hl(0, 'LspInlayHint', {fg='#a28e92', bg='#eeeeee'})
  vim.api.nvim_set_hl(0, 'LspReferenceRead', {bg='#e8ccc1'})
  vim.api.nvim_set_hl(0, 'LspReferenceTarget', {bg='#e8ccc1'})
  vim.api.nvim_set_hl(0, 'LspReferenceText', {bg='#e8ccc1'})
  vim.api.nvim_set_hl(0, 'LspReferenceWrite', {bg='#e8ccc1'})
  vim.api.nvim_set_hl(0, 'LspSignatureActiveParameter', {bg='#9eebe4'})
  vim.api.nvim_set_hl(0, 'Macro', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, 'MasonError', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'MasonHeader', {fg='#f3f3f3', bg='#53372a', bold=true})
  vim.api.nvim_set_hl(0, 'MasonHighlight', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'MasonHighlightBlock', {fg='#f3f3f3', bg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'MasonHighlightBlockBold', {fg='#f3f3f3', bg='#69a6a2', bold=true})
  vim.api.nvim_set_hl(0, 'MasonHighlightBlockBoldSecondary', {fg='#f3f3f3', bg='#53372a', bold=true})
  vim.api.nvim_set_hl(0, 'MasonHighlightBlockSecondary', {fg='#f3f3f3', bg='#53372a'})
  vim.api.nvim_set_hl(0, 'MasonHighlightSecondary', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'MasonMuted', {fg='#486f6c'})
  vim.api.nvim_set_hl(0, 'MasonMutedBlock', {fg='#f3f3f3', bg='#486f6c'})
  vim.api.nvim_set_hl(0, 'MasonMutedBlockBold', {fg='#f3f3f3', bg='#486f6c', bold=true})
  vim.api.nvim_set_hl(0, 'MatchParen', {fg='#28403e', bg='#dfc0da'})
  vim.api.nvim_set_hl(0, 'ModeMsg', {fg='#28403e', bg='#f3f3f3'})
  vim.api.nvim_set_hl(0, 'MoreMsg', {fg='#807750', bold=true})
  vim.api.nvim_set_hl(0, 'MsgSeparator', {bg='#f3f3f3'})
  vim.api.nvim_set_hl(0, 'NeogitDiffAddHighlight', {bg='#ece2be'})
  vim.api.nvim_set_hl(0, 'NeogitDiffContextHighlight', {bg='#ebebeb'})
  vim.api.nvim_set_hl(0, 'NeogitDiffDeleteHighlight', {bg='#eedeec'})
  vim.api.nvim_set_hl(0, 'NeogitHunkHeader', {fg='#9b9b9b'})
  vim.api.nvim_set_hl(0, 'NeogitHunkHeaderHighlight', {fg='#28403e', bg='#ebebeb', bold=true})
  vim.api.nvim_set_hl(0, 'NeogitNotificationError', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NeogitNotificationInfo', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'NeogitNotificationWarning', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'NnnNormal', {fg='#28403e', bg='#ebebeb'})
  vim.api.nvim_set_hl(0, 'NnnNormalNC', {fg='#28403e', bg='#ebebeb'})
  vim.api.nvim_set_hl(0, 'NnnVertSplit', {fg='#f3f3f3'})
  vim.api.nvim_set_hl(0, 'NnnWinSeparator', {fg='#f3f3f3'})
  vim.api.nvim_set_hl(0, 'NoiceCmdlineIcon', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'NoiceCmdlineIconSearch', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupBorder', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupBorderSearch', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupTitle', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'NoiceCompletionItemKindDefault', {fg='#486f6c'})
  vim.api.nvim_set_hl(0, 'NoiceConfirmBorder', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'NonText', {fg='#b0b0b0'})
  vim.api.nvim_set_hl(0, 'Normal', {fg='#28403e', bg='#f3f3f3'})
  vim.api.nvim_set_hl(0, 'NormalFloat', {bg='#dddddd'})
  vim.api.nvim_set_hl(0, 'NotifyDEBUGIcon', {fg='#a5679c'})
  vim.api.nvim_set_hl(0, 'NotifyDEBUGTitle', {fg='#a5679c'})
  vim.api.nvim_set_hl(0, 'NotifyERRORIcon', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NotifyERRORTitle', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NotifyINFOIcon', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'NotifyINFOTitle', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'NotifyTRACEIcon', {fg='#a5679c'})
  vim.api.nvim_set_hl(0, 'NotifyTRACETitle', {fg='#a5679c'})
  vim.api.nvim_set_hl(0, 'NotifyWARNIcon', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'NotifyWARNTitle', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'Number', {fg='#486f6c'})
  vim.api.nvim_set_hl(0, 'NvimAnd', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimArrow', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'NvimAssignment', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimAssignmentWithAddition', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimAssignmentWithConcatenation', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimAssignmentWithSubtraction', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimAugmentedAssignment', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimBinaryMinus', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimBinaryOperator', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimBinaryPlus', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimCallingParenthesis', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'NvimColon', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'NvimComma', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'NvimComparison', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimComparisonModifier', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimConcat', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimConcatOrSubscript', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimContainer', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'NvimCurly', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'NvimDict', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'NvimDivision', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimDoubleQuote', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'NvimDoubleQuotedBody', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'NvimDoubleQuotedEscape', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'NvimDoubleQuotedUnknownEscape', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimEnvironmentName', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, 'NvimEnvironmentSigil', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, 'NvimFigureBrace', {fg='#ff0000', bg='#ff0000'})
  vim.api.nvim_set_hl(0, 'NvimFloat', {fg='#486f6c'})
  vim.api.nvim_set_hl(0, 'NvimIdentifier', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, 'NvimIdentifierKey', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, 'NvimIdentifierName', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, 'NvimIdentifierScope', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, 'NvimIdentifierScopeDelimiter', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, 'NvimInternalError', {fg='#ff0000', bg='#ff0000'})
  vim.api.nvim_set_hl(0, 'NvimInvalid', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidAnd', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidArrow', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidAssignment', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidAssignmentWithAddition', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidAssignmentWithConcatenation', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidAssignmentWithSubtraction', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidAugmentedAssignment', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidBinaryMinus', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidBinaryOperator', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidBinaryPlus', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidCallingParenthesis', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidColon', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidComma', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidComparison', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidComparisonModifier', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidConcat', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidConcatOrSubscript', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidContainer', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidCurly', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidDelimiter', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidDict', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidDivision', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidDoubleQuote', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidDoubleQuotedBody', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'NvimInvalidDoubleQuotedEscape', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'NvimInvalidDoubleQuotedUnknownEscape', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidEnvironmentName', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidEnvironmentSigil', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidFigureBrace', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidFloat', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidIdentifier', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidIdentifierKey', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidIdentifierName', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidIdentifierScope', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidIdentifierScopeDelimiter', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidLambda', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidList', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidMod', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidMultiplication', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidNestingParenthesis', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidNot', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidNumber', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidNumberPrefix', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidOperator', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidOptionName', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidOptionScope', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidOptionScopeDelimiter', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidOptionSigil', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidOr', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidParenthesis', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidPlainAssignment', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidRegister', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidSingleQuote', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidSingleQuotedBody', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'NvimInvalidSingleQuotedQuote', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'NvimInvalidSingleQuotedUnknownEscape', {fg='#ff0000', bg='#ff0000'})
  vim.api.nvim_set_hl(0, 'NvimInvalidSpacing', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidString', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidStringBody', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'NvimInvalidStringQuote', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidStringSpecial', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'NvimInvalidSubscript', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidSubscriptBracket', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidSubscriptColon', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidTernary', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidTernaryColon', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidUnaryMinus', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidUnaryOperator', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidUnaryPlus', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimInvalidValue', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'NvimLambda', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'NvimList', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'NvimMod', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimMultiplication', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimNestingParenthesis', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'NvimNot', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimNumber', {fg='#486f6c'})
  vim.api.nvim_set_hl(0, 'NvimNumberPrefix', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, 'NvimOperator', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimOptionName', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, 'NvimOptionScope', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, 'NvimOptionScopeDelimiter', {fg='#3a5b58'})
  vim.api.nvim_set_hl(0, 'NvimOptionSigil', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, 'NvimOr', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimParenthesis', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'NvimPlainAssignment', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimRegister', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'NvimSingleQuote', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'NvimSingleQuotedBody', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'NvimSingleQuotedQuote', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'NvimSingleQuotedUnknownEscape', {fg='#ff0000', bg='#ff0000'})
  vim.api.nvim_set_hl(0, 'NvimSpacing', {fg='#28403e', bg='#f3f3f3'})
  vim.api.nvim_set_hl(0, 'NvimString', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'NvimStringBody', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'NvimStringQuote', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'NvimStringSpecial', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'NvimSubscript', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'NvimSubscriptBracket', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'NvimSubscriptColon', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'NvimTernary', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimTernaryColon', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimTreeCursorColumn', {bg='#e2e2e2'})
  vim.api.nvim_set_hl(0, 'NvimTreeCursorLine', {bg='#e2e2e2'})
  vim.api.nvim_set_hl(0, 'NvimTreeGitDeleted', {bg='#eedeec'})
  vim.api.nvim_set_hl(0, 'NvimTreeGitDirty', {bg='#c1eae7'})
  vim.api.nvim_set_hl(0, 'NvimTreeGitNew', {bg='#ece2be'})
  vim.api.nvim_set_hl(0, 'NvimTreeNormal', {fg='#28403e', bg='#ebebeb'})
  vim.api.nvim_set_hl(0, 'NvimTreeRootFolder', {fg='#69a6a2', bold=true})
  vim.api.nvim_set_hl(0, 'NvimTreeSpecialFile', {fg='#a5679c', underline=true})
  vim.api.nvim_set_hl(0, 'NvimTreeSymlink', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'NvimTreeWinSeparator', {fg='#f3f3f3'})
  vim.api.nvim_set_hl(0, 'NvimUnaryMinus', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimUnaryOperator', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'NvimUnaryPlus', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'OkMsg', {fg='#005523'})
  vim.api.nvim_set_hl(0, 'Operator', {fg='#14161b'})
  vim.api.nvim_set_hl(0, 'Pmenu', {bg='#d7d7d7'})
  vim.api.nvim_set_hl(0, 'PmenuBorder', {bg='#d7d7d7'})
  vim.api.nvim_set_hl(0, 'PmenuExtra', {bg='#d7d7d7'})
  vim.api.nvim_set_hl(0, 'PmenuExtraSel', {bg='#bebebe'})
  vim.api.nvim_set_hl(0, 'PmenuKind', {bg='#d7d7d7'})
  vim.api.nvim_set_hl(0, 'PmenuKindSel', {bg='#bebebe'})
  vim.api.nvim_set_hl(0, 'PmenuMatch', {bold=true})
  vim.api.nvim_set_hl(0, 'PmenuMatchSel', {bold=true})
  vim.api.nvim_set_hl(0, 'PmenuSbar', {bg='#a8a8a8'})
  vim.api.nvim_set_hl(0, 'PmenuSel', {bg='#bebebe'})
  vim.api.nvim_set_hl(0, 'PmenuShadow', {bg='#9b9ea4'})
  vim.api.nvim_set_hl(0, 'PmenuShadowThrough', {bg='#9b9ea4'})
  vim.api.nvim_set_hl(0, 'PmenuThumb', {bg='#f9f9f9'})
  vim.api.nvim_set_hl(0, 'PreCondit', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, 'PreInsert', {fg='#005523'})
  vim.api.nvim_set_hl(0, 'PreProc', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, 'Question', {fg='#807750', bold=true})
  vim.api.nvim_set_hl(0, 'QuickFixLine', {fg='#28403e', bg='#dfc0da'})
  vim.api.nvim_set_hl(0, 'RedrawDebugClear', {bg='#fce094'})
  vim.api.nvim_set_hl(0, 'RedrawDebugComposed', {bg='#b3f6c0'})
  vim.api.nvim_set_hl(0, 'RedrawDebugNormal', {reverse=true})
  vim.api.nvim_set_hl(0, 'RedrawDebugRecompose', {bg='#ffc0b9'})
  vim.api.nvim_set_hl(0, 'Removed', {fg='#590008'})
  vim.api.nvim_set_hl(0, 'RenderMarkdownCode', {bg='#eeeeee'})
  vim.api.nvim_set_hl(0, 'Repeat', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, 'Search', {fg='#28403e', bg='#dfc0da'})
  vim.api.nvim_set_hl(0, 'SignColumn', {fg='#9b9b9b'})
  vim.api.nvim_set_hl(0, 'SnacksIndent', {fg='#e2e2e2'})
  vim.api.nvim_set_hl(0, 'SnacksIndentScope', {fg='#b9b9b9'})
  vim.api.nvim_set_hl(0, 'SnacksPickerBorder', {bg='#dddddd'})
  vim.api.nvim_set_hl(0, 'SnacksPickerListCursorLine', {bg='#ebebeb'})
  vim.api.nvim_set_hl(0, 'SnacksPickerMatch', {fg='#a5679c', bold=true})
  vim.api.nvim_set_hl(0, 'SnacksPickerPreviewCursorLine', {bg='#ebebeb'})
  vim.api.nvim_set_hl(0, 'Sneak', {fg='#28403e', bg='#dfc0da'})
  vim.api.nvim_set_hl(0, 'SneakLabel', {fg='#f3f3f3', bg='#a5679c'})
  vim.api.nvim_set_hl(0, 'SneakLabelMask', {fg='#a5679c', bg='#a5679c'})
  vim.api.nvim_set_hl(0, 'SnippetTabstop', {bg='#9eebe4'})
  vim.api.nvim_set_hl(0, 'SnippetTabstopActive', {bg='#9eebe4'})
  vim.api.nvim_set_hl(0, 'Special', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'SpecialChar', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'SpecialComment', {fg='#919191'})
  vim.api.nvim_set_hl(0, 'SpecialKey', {fg='#b0b0b0', italic=true})
  vim.api.nvim_set_hl(0, 'SpellBad', {fg='#7f5d7b', sp='#895883', undercurl=true})
  vim.api.nvim_set_hl(0, 'SpellCap', {fg='#7f5d7b', sp='#9c6495', undercurl=true})
  vim.api.nvim_set_hl(0, 'SpellLocal', {fg='#7f5d7b', sp='#9c6495', undercurl=true})
  vim.api.nvim_set_hl(0, 'SpellRare', {fg='#7f5d7b', sp='#53372a', undercurl=true})
  vim.api.nvim_set_hl(0, 'Statement', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, 'StatusLine', {bg='#f3f3f3'})
  vim.api.nvim_set_hl(0, 'StatusLineNC', {bg='#f3f3f3'})
  vim.api.nvim_set_hl(0, 'StatusLineTerm', {bg='#f3f3f3'})
  vim.api.nvim_set_hl(0, 'StatusLineTermNC', {bg='#f3f3f3'})
  vim.api.nvim_set_hl(0, 'StderrMsg', {fg='#895883'})
  vim.api.nvim_set_hl(0, 'StorageClass', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, 'String', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'Structure', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, 'Substitute', {fg='#28403e', bg='#dfc0da'})
  vim.api.nvim_set_hl(0, 'TabLine', {fg='#818181', bg='#cfcfcf'})
  vim.api.nvim_set_hl(0, 'TabLineFill', {bg='#e8e8e8'})
  vim.api.nvim_set_hl(0, 'TabLineSel', {bold=true})
  vim.api.nvim_set_hl(0, 'Tag', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'TelescopeBorder', {fg='#727272'})
  vim.api.nvim_set_hl(0, 'TelescopeMatching', {fg='#a5679c', bold=true})
  vim.api.nvim_set_hl(0, 'TelescopeSelection', {bg='#ebebeb'})
  vim.api.nvim_set_hl(0, 'TelescopeSelectionCaret', {fg='#895883', bg='#ebebeb'})
  vim.api.nvim_set_hl(0, 'TermCursor', {fg='#f3f3f3', bg='#28403e'})
  vim.api.nvim_set_hl(0, 'TermCursorNC', {fg='#f3f3f3', bg='#416562'})
  vim.api.nvim_set_hl(0, 'Title', {fg='#28403e', bold=true})
  vim.api.nvim_set_hl(0, 'Todo', {bold=true, underline=true})
  vim.api.nvim_set_hl(0, 'TroubleNormal', {fg='#28403e'})
  vim.api.nvim_set_hl(0, 'TroubleSource', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'TroubleText', {fg='#28403e'})
  vim.api.nvim_set_hl(0, 'Type', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, 'Typedef', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, 'Underlined', {underline=true})
  vim.api.nvim_set_hl(0, 'VertSplit', {fg='#9b9b9b'})
  vim.api.nvim_set_hl(0, 'Visual', {bg='#9eebe4'})
  vim.api.nvim_set_hl(0, 'VisualNOS', {bg='#9eebe4'})
  vim.api.nvim_set_hl(0, 'WarningMsg', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'WhichKey', {fg='#895883', bold=true})
  vim.api.nvim_set_hl(0, 'WhichKeyGroup', {fg='#69a6a2'})
  vim.api.nvim_set_hl(0, 'WhichKeySeparator', {fg='#9b9b9b'})
  vim.api.nvim_set_hl(0, 'WhichKeyValue', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'Whitespace', {fg='#b0b0b0'})
  vim.api.nvim_set_hl(0, 'WildMenu', {fg='#f3f3f3', bg='#a5679c'})
  vim.api.nvim_set_hl(0, 'WinBar', {bg='#f3f3f3'})
  vim.api.nvim_set_hl(0, 'WinBarNC', {bg='#f3f3f3'})
  vim.api.nvim_set_hl(0, 'WinSeparator', {fg='#9b9b9b'})
  vim.api.nvim_set_hl(0, 'diffAdded', {bg='#ece2be'})
  vim.api.nvim_set_hl(0, 'diffChanged', {bg='#c1eae7'})
  vim.api.nvim_set_hl(0, 'diffFile', {fg='#53372a', bold=true})
  vim.api.nvim_set_hl(0, 'diffIndexLine', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'diffLine', {fg='#a5679c', bold=true})
  vim.api.nvim_set_hl(0, 'diffNewFile', {fg='#807750', italic=true})
  vim.api.nvim_set_hl(0, 'diffOldFile', {fg='#895883', italic=true})
  vim.api.nvim_set_hl(0, 'diffRemoved', {bg='#eedeec'})
  vim.api.nvim_set_hl(0, 'gitcommitOverflow', {fg='#53372a'})
  vim.api.nvim_set_hl(0, 'helpHyperTextEntry', {fg='#735057', bold=true})
  vim.api.nvim_set_hl(0, 'helpHyperTextJump', {fg='#3a5b58', underline=true})
  vim.api.nvim_set_hl(0, 'helpOption', {fg='#486f6c', italic=true})
  vim.api.nvim_set_hl(0, 'helpSpecial', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, 'lCursor', {fg='#f3f3f3', bg='#416562'})
  vim.api.nvim_set_hl(0, 'markdownCode', {fg='#7bc3bd', italic=true})
  vim.api.nvim_set_hl(0, 'markdownLinkText', {fg='#3a5b58', underline=true})
  vim.api.nvim_set_hl(0, 'markdownLinkTextDelimiter', {fg='#868686'})
  vim.api.nvim_set_hl(0, 'markdownUrl', {fg='#919191'})
  vim.api.nvim_set_hl(0, 'nvim_set_hl_x_hi_clear_bugfix', {fg='#ff0000'})
else
  vim.api.nvim_set_hl(0, '@attribute', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@attribute.builtin', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@boolean', {fg='#ebdcb4', italic=true})
  vim.api.nvim_set_hl(0, '@character', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@character.special', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@comment', {fg='#727272', italic=true})
  vim.api.nvim_set_hl(0, '@comment.documentation', {fg='#727272', italic=true})
  vim.api.nvim_set_hl(0, '@comment.error', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, '@comment.note', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@comment.todo', {bold=true, underline=true})
  vim.api.nvim_set_hl(0, '@comment.warning', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, '@constant', {fg='#c9ba94', bold=true})
  vim.api.nvim_set_hl(0, '@constant.builtin', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@constant.macro', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@constructor', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@constructor.lua', {fg='#848484'})
  vim.api.nvim_set_hl(0, '@diff.delta', {bg='#273e35'})
  vim.api.nvim_set_hl(0, '@diff.minus', {bg='#52302e'})
  vim.api.nvim_set_hl(0, '@diff.plus', {bg='#3a3a25'})
  vim.api.nvim_set_hl(0, '@function', {fg='#ebdcb4'})
  vim.api.nvim_set_hl(0, '@function.builtin', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@function.call', {fg='#ebdcb4'})
  vim.api.nvim_set_hl(0, '@function.macro', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@function.method', {fg='#ebdcb4'})
  vim.api.nvim_set_hl(0, '@function.method.call', {fg='#ebdcb4'})
  vim.api.nvim_set_hl(0, '@keyword', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.conditional', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.conditional.ternary', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.coroutine', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.debug', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@keyword.directive', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.directive.define', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.exception', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.function', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.import', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.operator', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.repeat', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.return', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@keyword.storage', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@label', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@label.vimdoc', {fg='#9e9e9e', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.mod.deprecated', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, '@lsp.type.boolean', {fg='#ebdcb4', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.builtinType', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.class', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.comment', {fg='#727272', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.decorator', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.type.deriveHelper', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.type.enum', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.enumMember', {fg='#c9ba94', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.type.escapeSequence', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@lsp.type.event', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.formatSpecifier', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@lsp.type.function', {fg='#ebdcb4'})
  vim.api.nvim_set_hl(0, '@lsp.type.generic', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, '@lsp.type.interface', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.keyword', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.type.lifetime', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.macro', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.method', {fg='#ebdcb4'})
  vim.api.nvim_set_hl(0, '@lsp.type.modifier', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.namespace', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.number', {fg='#afa280'})
  vim.api.nvim_set_hl(0, '@lsp.type.operator', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.type.parameter', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, '@lsp.type.property', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, '@lsp.type.regexp', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.selfKeyword', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.selfTypeKeyword', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.string', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.struct', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.type', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.typeAlias', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.typeParameter', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.type.unresolvedReference', {sp='#fb4c36', undercurl=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.class.defaultLibrary', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.enum.defaultLibrary', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.enumMember.defaultLibrary', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.function.defaultLibrary', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@lsp.typemod.keyword.async', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.keyword.injected', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.macro.defaultLibrary', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@lsp.typemod.method.defaultLibrary', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@lsp.typemod.operator.injected', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.string.injected', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.struct.defaultLibrary', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.type.defaultLibrary', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.typeAlias.defaultLibrary', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.variable.callable', {fg='#ebdcb4'})
  vim.api.nvim_set_hl(0, '@lsp.typemod.variable.defaultLibrary', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@lsp.typemod.variable.injected', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, '@lsp.typemod.variable.static', {fg='#c9ba94', bold=true})
  vim.api.nvim_set_hl(0, '@markup', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@markup.environment', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@markup.heading', {fg='#ebdcb4', bold=true})
  vim.api.nvim_set_hl(0, '@markup.heading.1.delimiter.vimdoc', {fg='#282828', bg='#282828', sp='#ebdcb4'})
  vim.api.nvim_set_hl(0, '@markup.heading.2.delimiter.vimdoc', {fg='#282828', bg='#282828', sp='#ebdcb4', underline=true})
  vim.api.nvim_set_hl(0, '@markup.italic', {italic=true})
  vim.api.nvim_set_hl(0, '@markup.italic.markdown', {italic=true})
  vim.api.nvim_set_hl(0, '@markup.link', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@markup.link.label', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@markup.link.markdown', {fg='#c9ba94', underline=true})
  vim.api.nvim_set_hl(0, '@markup.link.url', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@markup.link.url.markdown', {fg='#727272'})
  vim.api.nvim_set_hl(0, '@markup.link.vimdoc', {fg='#c9ba94', underline=true})
  vim.api.nvim_set_hl(0, '@markup.list', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@markup.list.checked', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@markup.list.unchecked', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@markup.math', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@markup.quote', {fg='#afa280'})
  vim.api.nvim_set_hl(0, '@markup.raw', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@markup.raw.block', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@markup.raw.markdown', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@markup.strikethrough', {strikethrough=true})
  vim.api.nvim_set_hl(0, '@markup.strong', {bold=true})
  vim.api.nvim_set_hl(0, '@markup.title.markdown', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@markup.underline', {underline=true})
  vim.api.nvim_set_hl(0, '@module', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@module.builtin', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@number', {fg='#afa280'})
  vim.api.nvim_set_hl(0, '@number.float', {fg='#afa280'})
  vim.api.nvim_set_hl(0, '@operator', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, '@property', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, '@punctuation', {fg='#848484'})
  vim.api.nvim_set_hl(0, '@punctuation.bracket', {fg='#848484'})
  vim.api.nvim_set_hl(0, '@punctuation.delimiter', {fg='#848484'})
  vim.api.nvim_set_hl(0, '@punctuation.special', {fg='#848484'})
  vim.api.nvim_set_hl(0, '@punctuation.special.markdown', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@string', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@string.documentation', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@string.escape', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@string.escape.markdown', {fg='#616161', italic=true})
  vim.api.nvim_set_hl(0, '@string.regexp', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@string.special', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@string.special.path', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@string.special.symbol', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, '@string.special.url', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@tag', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@tag.attribute', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, '@tag.builtin', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@tag.delimiter', {fg='#848484'})
  vim.api.nvim_set_hl(0, '@type', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@type.builtin', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@type.definition', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@type.qualifier', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, '@variable', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, '@variable.builtin', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, '@variable.member', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, '@variable.parameter', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, '@variable.parameter.builtin', {fg='#83a598'})
  vim.api.nvim_set_hl(0, '@variable.parameter.vimdoc', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, 'Added', {fg='#b3f6c0'})
  vim.api.nvim_set_hl(0, 'BlinkCmpKind', {fg='#afa280'})
  vim.api.nvim_set_hl(0, 'BlinkCmpLabelDescription', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, 'BlinkCmpLabelDetail', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, 'BlinkCmpSource', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, 'Bold', {bold=true})
  vim.api.nvim_set_hl(0, 'Boolean', {fg='#ebdcb4', italic=true})
  vim.api.nvim_set_hl(0, 'BufferCurrent', {bold=true})
  vim.api.nvim_set_hl(0, 'BufferVisible', {fg='#f0e4ca'})
  vim.api.nvim_set_hl(0, 'BufferVisibleIndex', {fg='#f0e4ca'})
  vim.api.nvim_set_hl(0, 'BufferVisibleSign', {fg='#f0e4ca'})
  vim.api.nvim_set_hl(0, 'Changed', {fg='#8cf8f7'})
  vim.api.nvim_set_hl(0, 'Character', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'CmpItemAbbr', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, 'CmpItemAbbrDeprecated', {fg='#83795f'})
  vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch', {fg='#ebdcb4', bold=true})
  vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzy', {fg='#d2c39a', bold=true})
  vim.api.nvim_set_hl(0, 'CmpItemKind', {fg='#afa280'})
  vim.api.nvim_set_hl(0, 'CmpItemMenu', {fg='#a19576'})
  vim.api.nvim_set_hl(0, 'CocCodeLens', {fg='#6a6a6a'})
  vim.api.nvim_set_hl(0, 'CocErrorHighlight', {sp='#fb4c36', undercurl=true})
  vim.api.nvim_set_hl(0, 'CocErrorSign', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'CocErrorVirtualText', {fg='#fb4c36', bg='#372e2e'})
  vim.api.nvim_set_hl(0, 'CocHintHighlight', {sp='#d2859a', undercurl=true})
  vim.api.nvim_set_hl(0, 'CocHintSign', {fg='#d2859a'})
  vim.api.nvim_set_hl(0, 'CocInfoHighlight', {sp='#83a598', undercurl=true})
  vim.api.nvim_set_hl(0, 'CocInfoSign', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'CocMarkdownLink', {fg='#82c07b', underline=true})
  vim.api.nvim_set_hl(0, 'CocMenuSel', {bg='#2e2e2e'})
  vim.api.nvim_set_hl(0, 'CocSearch', {fg='#ebdcb4', bg='#93455d'})
  vim.api.nvim_set_hl(0, 'CocSelectedText', {fg='#e46258', undercurl=true})
  vim.api.nvim_set_hl(0, 'CocWarningHighlight', {sp='#f9bd30', undercurl=true})
  vim.api.nvim_set_hl(0, 'CocWarningSign', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'CocWarningVirtualText', {fg='#f9bd30', bg='#32302e'})
  vim.api.nvim_set_hl(0, 'ColorColumn', {bg='#5d4e38'})
  vim.api.nvim_set_hl(0, 'Comment', {fg='#727272', italic=true})
  vim.api.nvim_set_hl(0, 'ComplHint', {fg='#616161'})
  vim.api.nvim_set_hl(0, 'ComplHintMore', {fg='#b7ba26', bold=true})
  vim.api.nvim_set_hl(0, 'Conceal', {fg='#a19576', bold=true, italic=true})
  vim.api.nvim_set_hl(0, 'Conditional', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, 'Constant', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'CurSearch', {fg='#282828', bg='#dba1b0', bold=true})
  vim.api.nvim_set_hl(0, 'Cursor', {fg='#282828', bg='#eee2c3'})
  vim.api.nvim_set_hl(0, 'CursorColumn', {bg='#2e2e2e'})
  vim.api.nvim_set_hl(0, 'CursorIM', {fg='#282828', bg='#eee2c3'})
  vim.api.nvim_set_hl(0, 'CursorLine', {bg='#2e2e2e'})
  vim.api.nvim_set_hl(0, 'CursorLineFold', {fg='#6a6a6a', bold=true})
  vim.api.nvim_set_hl(0, 'CursorLineNr', {fg='#ebdcb4', bold=true})
  vim.api.nvim_set_hl(0, 'CursorLineSign', {fg='#6a6a6a'})
  vim.api.nvim_set_hl(0, 'Debug', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'Define', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, 'Delimiter', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'DiagnosticDeprecated', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'DiagnosticError', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'DiagnosticFloatingError', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'DiagnosticFloatingHint', {fg='#d2859a'})
  vim.api.nvim_set_hl(0, 'DiagnosticFloatingInfo', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'DiagnosticFloatingOk', {fg='#b7ba26'})
  vim.api.nvim_set_hl(0, 'DiagnosticFloatingWarn', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'DiagnosticHint', {fg='#d2859a'})
  vim.api.nvim_set_hl(0, 'DiagnosticInfo', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'DiagnosticOk', {fg='#b7ba26'})
  vim.api.nvim_set_hl(0, 'DiagnosticSignError', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'DiagnosticSignHint', {fg='#d2859a'})
  vim.api.nvim_set_hl(0, 'DiagnosticSignInfo', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'DiagnosticSignOk', {fg='#b7ba26'})
  vim.api.nvim_set_hl(0, 'DiagnosticSignWarn', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', {sp='#fb4c36', undercurl=true})
  vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint', {sp='#d2859a', undercurl=true})
  vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo', {sp='#83a598', undercurl=true})
  vim.api.nvim_set_hl(0, 'DiagnosticUnderlineOk', {sp='#b7ba26', undercurl=true})
  vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn', {sp='#f9bd30', undercurl=true})
  vim.api.nvim_set_hl(0, 'DiagnosticUnnecessary', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualLinesError', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualLinesHint', {fg='#d2859a'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualLinesInfo', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualLinesOk', {fg='#b7ba26'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualLinesWarn', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextError', {fg='#fb4c36', bg='#372e2e'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextHint', {fg='#d2859a', bg='#372e30'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextInfo', {fg='#83a598', bg='#2e3130'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextOk', {fg='#b7ba26', bg='#30302e'})
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextWarn', {fg='#f9bd30', bg='#32302e'})
  vim.api.nvim_set_hl(0, 'DiagnosticWarn', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'DiffAdd', {bg='#3a3a25'})
  vim.api.nvim_set_hl(0, 'DiffChange', {bg='#273e35'})
  vim.api.nvim_set_hl(0, 'DiffDelete', {bg='#52302e'})
  vim.api.nvim_set_hl(0, 'DiffText', {fg='#ebdcb4', bg='#3b5b4f'})
  vim.api.nvim_set_hl(0, 'DiffTextAdd', {fg='#ebdcb4', bg='#3b5b4f'})
  vim.api.nvim_set_hl(0, 'Directory', {bold=true})
  vim.api.nvim_set_hl(0, 'EndOfBuffer', {fg='#616161'})
  vim.api.nvim_set_hl(0, 'Error', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'ErrorMsg', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'Exception', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, 'FlashBackdrop', {fg='#727272'})
  vim.api.nvim_set_hl(0, 'FlashLabel', {fg='#ebdcb4', bg='#4e635b'})
  vim.api.nvim_set_hl(0, 'Float', {fg='#afa280'})
  vim.api.nvim_set_hl(0, 'FloatBorder', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'FloatFooter', {fg='#ebdcb4', bg='#393939', bold=true})
  vim.api.nvim_set_hl(0, 'FloatShadow', {bg='#4f5258'})
  vim.api.nvim_set_hl(0, 'FloatShadowThrough', {bg='#4f5258'})
  vim.api.nvim_set_hl(0, 'FloatTitle', {fg='#ebdcb4', bg='#393939', bold=true})
  vim.api.nvim_set_hl(0, 'FoldColumn', {fg='#6a6a6a', bold=true})
  vim.api.nvim_set_hl(0, 'Folded', {fg='#ebdcb4'})
  vim.api.nvim_set_hl(0, 'Function', {fg='#ebdcb4'})
  vim.api.nvim_set_hl(0, 'FzfLuaBufFlagAlt', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'FzfLuaBufFlagCur', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'FzfLuaBufName', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, 'FzfLuaBufNr', {fg='#b7ba26'})
  vim.api.nvim_set_hl(0, 'FzfLuaFzfCursorLine', {bg='#2e2e2e'})
  vim.api.nvim_set_hl(0, 'FzfLuaFzfMatch', {fg='#d2859a', bold=true})
  vim.api.nvim_set_hl(0, 'FzfLuaHeaderBind', {fg='#b7ba26'})
  vim.api.nvim_set_hl(0, 'FzfLuaHeaderText', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'FzfLuaLiveSym', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'FzfLuaPathColNr', {fg='#9e9e9e', bold=true})
  vim.api.nvim_set_hl(0, 'FzfLuaPathLineNr', {fg='#9e9e9e', bold=true})
  vim.api.nvim_set_hl(0, 'FzfLuaTabMarker', {fg='#b7ba26'})
  vim.api.nvim_set_hl(0, 'FzfLuaTabTitle', {fg='#82c07b'})
  vim.api.nvim_set_hl(0, 'FzfLuaTitle', {fg='#ebdcb4', bold=true})
  vim.api.nvim_set_hl(0, 'GitGutterAdd', {fg='#b7ba26'})
  vim.api.nvim_set_hl(0, 'GitGutterChange', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'GitGutterDelete', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'GitSignsAdd', {fg='#b7ba26'})
  vim.api.nvim_set_hl(0, 'GitSignsChange', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'GitSignsDelete', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'HopNextKey', {fg='#d2859a', bold=true, underline=true})
  vim.api.nvim_set_hl(0, 'HopNextKey1', {fg='#82c07b', bold=true, underline=true})
  vim.api.nvim_set_hl(0, 'HopNextKey2', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'HopUnmatched', {fg='#727272'})
  vim.api.nvim_set_hl(0, 'IblIndent', {fg='#373737'})
  vim.api.nvim_set_hl(0, 'IblScope', {fg='#505050'})
  vim.api.nvim_set_hl(0, 'Identifier', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, 'Ignore', {fg='#ebdcb4', bg='#282828'})
  vim.api.nvim_set_hl(0, 'IncSearch', {fg='#282828', bg='#dba1b0', bold=true})
  vim.api.nvim_set_hl(0, 'Include', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, 'IndentLine', {fg='#373737'})
  vim.api.nvim_set_hl(0, 'IndentLineCurrent', {fg='#505050'})
  vim.api.nvim_set_hl(0, 'Italic', {italic=true})
  vim.api.nvim_set_hl(0, 'Keyword', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, 'Label', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, 'LineNr', {fg='#6a6a6a'})
  vim.api.nvim_set_hl(0, 'LineNrAbove', {fg='#6a6a6a'})
  vim.api.nvim_set_hl(0, 'LineNrBelow', {fg='#6a6a6a'})
  vim.api.nvim_set_hl(0, 'LspCodeLens', {fg='#6a6a6a'})
  vim.api.nvim_set_hl(0, 'LspCodeLensSeparator', {fg='#6a6a6a'})
  vim.api.nvim_set_hl(0, 'LspInlayHint', {fg='#887175', bg='#2e2e2e'})
  vim.api.nvim_set_hl(0, 'LspReferenceRead', {bg='#5d4e38'})
  vim.api.nvim_set_hl(0, 'LspReferenceTarget', {bg='#5d4e38'})
  vim.api.nvim_set_hl(0, 'LspReferenceText', {bg='#5d4e38'})
  vim.api.nvim_set_hl(0, 'LspReferenceWrite', {bg='#5d4e38'})
  vim.api.nvim_set_hl(0, 'LspSignatureActiveParameter', {bg='#555041'})
  vim.api.nvim_set_hl(0, 'Macro', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, 'MasonError', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'MasonHeader', {fg='#282828', bg='#f9bd30', bold=true})
  vim.api.nvim_set_hl(0, 'MasonHighlight', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'MasonHighlightBlock', {fg='#282828', bg='#83a598'})
  vim.api.nvim_set_hl(0, 'MasonHighlightBlockBold', {fg='#282828', bg='#83a598', bold=true})
  vim.api.nvim_set_hl(0, 'MasonHighlightBlockBoldSecondary', {fg='#282828', bg='#f9bd30', bold=true})
  vim.api.nvim_set_hl(0, 'MasonHighlightBlockSecondary', {fg='#282828', bg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'MasonHighlightSecondary', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'MasonMuted', {fg='#afa280'})
  vim.api.nvim_set_hl(0, 'MasonMutedBlock', {fg='#282828', bg='#afa280'})
  vim.api.nvim_set_hl(0, 'MasonMutedBlockBold', {fg='#282828', bg='#afa280', bold=true})
  vim.api.nvim_set_hl(0, 'MatchParen', {fg='#ebdcb4', bg='#93455d'})
  vim.api.nvim_set_hl(0, 'ModeMsg', {fg='#ebdcb4', bg='#282828'})
  vim.api.nvim_set_hl(0, 'MoreMsg', {fg='#b7ba26', bold=true})
  vim.api.nvim_set_hl(0, 'MsgSeparator', {bg='#282828'})
  vim.api.nvim_set_hl(0, 'NeogitDiffAddHighlight', {bg='#3a3a25'})
  vim.api.nvim_set_hl(0, 'NeogitDiffContextHighlight', {bg='#2e2e2e'})
  vim.api.nvim_set_hl(0, 'NeogitDiffDeleteHighlight', {bg='#52302e'})
  vim.api.nvim_set_hl(0, 'NeogitHunkHeader', {fg='#6a6a6a'})
  vim.api.nvim_set_hl(0, 'NeogitHunkHeaderHighlight', {fg='#ebdcb4', bg='#2e2e2e', bold=true})
  vim.api.nvim_set_hl(0, 'NeogitNotificationError', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NeogitNotificationInfo', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'NeogitNotificationWarning', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'NnnNormal', {fg='#ebdcb4', bg='#2e2e2e'})
  vim.api.nvim_set_hl(0, 'NnnNormalNC', {fg='#ebdcb4', bg='#2e2e2e'})
  vim.api.nvim_set_hl(0, 'NnnVertSplit', {fg='#282828'})
  vim.api.nvim_set_hl(0, 'NnnWinSeparator', {fg='#282828'})
  vim.api.nvim_set_hl(0, 'NoiceCmdlineIcon', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'NoiceCmdlineIconSearch', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupBorder', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupBorderSearch', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupTitle', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'NoiceCompletionItemKindDefault', {fg='#afa280'})
  vim.api.nvim_set_hl(0, 'NoiceConfirmBorder', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'NonText', {fg='#616161'})
  vim.api.nvim_set_hl(0, 'Normal', {fg='#ebdcb4', bg='#282828'})
  vim.api.nvim_set_hl(0, 'NormalFloat', {bg='#393939'})
  vim.api.nvim_set_hl(0, 'NotifyDEBUGIcon', {fg='#d2859a'})
  vim.api.nvim_set_hl(0, 'NotifyDEBUGTitle', {fg='#d2859a'})
  vim.api.nvim_set_hl(0, 'NotifyERRORIcon', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NotifyERRORTitle', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NotifyINFOIcon', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'NotifyINFOTitle', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'NotifyTRACEIcon', {fg='#d2859a'})
  vim.api.nvim_set_hl(0, 'NotifyTRACETitle', {fg='#d2859a'})
  vim.api.nvim_set_hl(0, 'NotifyWARNIcon', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'NotifyWARNTitle', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'Number', {fg='#afa280'})
  vim.api.nvim_set_hl(0, 'NvimAnd', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimArrow', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'NvimAssignment', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimAssignmentWithAddition', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimAssignmentWithConcatenation', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimAssignmentWithSubtraction', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimAugmentedAssignment', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimBinaryMinus', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimBinaryOperator', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimBinaryPlus', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimCallingParenthesis', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'NvimColon', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'NvimComma', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'NvimComparison', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimComparisonModifier', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimConcat', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimConcatOrSubscript', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimContainer', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'NvimCurly', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'NvimDict', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'NvimDivision', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimDoubleQuote', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'NvimDoubleQuotedBody', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'NvimDoubleQuotedEscape', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'NvimDoubleQuotedUnknownEscape', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimEnvironmentName', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, 'NvimEnvironmentSigil', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, 'NvimFigureBrace', {fg='#ff0000', bg='#ff0000'})
  vim.api.nvim_set_hl(0, 'NvimFloat', {fg='#afa280'})
  vim.api.nvim_set_hl(0, 'NvimIdentifier', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, 'NvimIdentifierKey', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, 'NvimIdentifierName', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, 'NvimIdentifierScope', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, 'NvimIdentifierScopeDelimiter', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, 'NvimInternalError', {fg='#ff0000', bg='#ff0000'})
  vim.api.nvim_set_hl(0, 'NvimInvalid', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidAnd', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidArrow', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidAssignment', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidAssignmentWithAddition', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidAssignmentWithConcatenation', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidAssignmentWithSubtraction', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidAugmentedAssignment', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidBinaryMinus', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidBinaryOperator', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidBinaryPlus', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidCallingParenthesis', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidColon', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidComma', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidComparison', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidComparisonModifier', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidConcat', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidConcatOrSubscript', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidContainer', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidCurly', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidDelimiter', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidDict', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidDivision', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidDoubleQuote', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidDoubleQuotedBody', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'NvimInvalidDoubleQuotedEscape', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'NvimInvalidDoubleQuotedUnknownEscape', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidEnvironmentName', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidEnvironmentSigil', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidFigureBrace', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidFloat', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidIdentifier', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidIdentifierKey', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidIdentifierName', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidIdentifierScope', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidIdentifierScopeDelimiter', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidLambda', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidList', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidMod', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidMultiplication', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidNestingParenthesis', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidNot', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidNumber', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidNumberPrefix', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidOperator', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidOptionName', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidOptionScope', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidOptionScopeDelimiter', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidOptionSigil', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidOr', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidParenthesis', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidPlainAssignment', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidRegister', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidSingleQuote', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidSingleQuotedBody', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'NvimInvalidSingleQuotedQuote', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'NvimInvalidSingleQuotedUnknownEscape', {fg='#ff0000', bg='#ff0000'})
  vim.api.nvim_set_hl(0, 'NvimInvalidSpacing', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidString', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidStringBody', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'NvimInvalidStringQuote', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidStringSpecial', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'NvimInvalidSubscript', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidSubscriptBracket', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidSubscriptColon', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidTernary', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidTernaryColon', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidUnaryMinus', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidUnaryOperator', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidUnaryPlus', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimInvalidValue', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'NvimLambda', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'NvimList', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'NvimMod', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimMultiplication', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimNestingParenthesis', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'NvimNot', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimNumber', {fg='#afa280'})
  vim.api.nvim_set_hl(0, 'NvimNumberPrefix', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, 'NvimOperator', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimOptionName', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, 'NvimOptionScope', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, 'NvimOptionScopeDelimiter', {fg='#c9ba94'})
  vim.api.nvim_set_hl(0, 'NvimOptionSigil', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, 'NvimOr', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimParenthesis', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'NvimPlainAssignment', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimRegister', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'NvimSingleQuote', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'NvimSingleQuotedBody', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'NvimSingleQuotedQuote', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'NvimSingleQuotedUnknownEscape', {fg='#ff0000', bg='#ff0000'})
  vim.api.nvim_set_hl(0, 'NvimSpacing', {fg='#ebdcb4', bg='#282828'})
  vim.api.nvim_set_hl(0, 'NvimString', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'NvimStringBody', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'NvimStringQuote', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'NvimStringSpecial', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'NvimSubscript', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'NvimSubscriptBracket', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'NvimSubscriptColon', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'NvimTernary', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimTernaryColon', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimTreeCursorColumn', {bg='#323232'})
  vim.api.nvim_set_hl(0, 'NvimTreeCursorLine', {bg='#323232'})
  vim.api.nvim_set_hl(0, 'NvimTreeGitDeleted', {bg='#52302e'})
  vim.api.nvim_set_hl(0, 'NvimTreeGitDirty', {bg='#273e35'})
  vim.api.nvim_set_hl(0, 'NvimTreeGitNew', {bg='#3a3a25'})
  vim.api.nvim_set_hl(0, 'NvimTreeNormal', {fg='#ebdcb4', bg='#2e2e2e'})
  vim.api.nvim_set_hl(0, 'NvimTreeRootFolder', {fg='#83a598', bold=true})
  vim.api.nvim_set_hl(0, 'NvimTreeSpecialFile', {fg='#d2859a', underline=true})
  vim.api.nvim_set_hl(0, 'NvimTreeSymlink', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'NvimTreeWinSeparator', {fg='#282828'})
  vim.api.nvim_set_hl(0, 'NvimUnaryMinus', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimUnaryOperator', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'NvimUnaryPlus', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'OkMsg', {fg='#b3f6c0'})
  vim.api.nvim_set_hl(0, 'Operator', {fg='#e0e2ea'})
  vim.api.nvim_set_hl(0, 'Pmenu', {bg='#393939'})
  vim.api.nvim_set_hl(0, 'PmenuBorder', {bg='#393939'})
  vim.api.nvim_set_hl(0, 'PmenuExtra', {bg='#393939'})
  vim.api.nvim_set_hl(0, 'PmenuExtraSel', {bg='#505050'})
  vim.api.nvim_set_hl(0, 'PmenuKind', {bg='#393939'})
  vim.api.nvim_set_hl(0, 'PmenuKindSel', {bg='#505050'})
  vim.api.nvim_set_hl(0, 'PmenuMatch', {bold=true})
  vim.api.nvim_set_hl(0, 'PmenuMatchSel', {bold=true})
  vim.api.nvim_set_hl(0, 'PmenuSbar', {bg='#666666'})
  vim.api.nvim_set_hl(0, 'PmenuSel', {bg='#505050'})
  vim.api.nvim_set_hl(0, 'PmenuShadow', {bg='#4f5258'})
  vim.api.nvim_set_hl(0, 'PmenuShadowThrough', {bg='#4f5258'})
  vim.api.nvim_set_hl(0, 'PmenuThumb', {bg='#8b8b8b'})
  vim.api.nvim_set_hl(0, 'PreCondit', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, 'PreInsert', {fg='#b3f6c0'})
  vim.api.nvim_set_hl(0, 'PreProc', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, 'Question', {fg='#b7ba26', bold=true})
  vim.api.nvim_set_hl(0, 'QuickFixLine', {fg='#ebdcb4', bg='#93455d'})
  vim.api.nvim_set_hl(0, 'RedrawDebugClear', {bg='#6b5300'})
  vim.api.nvim_set_hl(0, 'RedrawDebugComposed', {bg='#005523'})
  vim.api.nvim_set_hl(0, 'RedrawDebugNormal', {reverse=true})
  vim.api.nvim_set_hl(0, 'RedrawDebugRecompose', {bg='#590008'})
  vim.api.nvim_set_hl(0, 'Removed', {fg='#ffc0b9'})
  vim.api.nvim_set_hl(0, 'RenderMarkdownCode', {bg='#2e2e2e'})
  vim.api.nvim_set_hl(0, 'Repeat', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, 'Search', {fg='#ebdcb4', bg='#93455d'})
  vim.api.nvim_set_hl(0, 'SignColumn', {fg='#6a6a6a'})
  vim.api.nvim_set_hl(0, 'SnacksIndent', {fg='#373737'})
  vim.api.nvim_set_hl(0, 'SnacksIndentScope', {fg='#505050'})
  vim.api.nvim_set_hl(0, 'SnacksPickerBorder', {bg='#393939'})
  vim.api.nvim_set_hl(0, 'SnacksPickerListCursorLine', {bg='#2e2e2e'})
  vim.api.nvim_set_hl(0, 'SnacksPickerMatch', {fg='#d2859a', bold=true})
  vim.api.nvim_set_hl(0, 'SnacksPickerPreviewCursorLine', {bg='#2e2e2e'})
  vim.api.nvim_set_hl(0, 'Sneak', {fg='#ebdcb4', bg='#93455d'})
  vim.api.nvim_set_hl(0, 'SneakLabel', {fg='#282828', bg='#d2859a'})
  vim.api.nvim_set_hl(0, 'SneakLabelMask', {fg='#d2859a', bg='#d2859a'})
  vim.api.nvim_set_hl(0, 'SnippetTabstop', {bg='#555041'})
  vim.api.nvim_set_hl(0, 'SnippetTabstopActive', {bg='#555041'})
  vim.api.nvim_set_hl(0, 'Special', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'SpecialChar', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'SpecialComment', {fg='#727272'})
  vim.api.nvim_set_hl(0, 'SpecialKey', {fg='#616161', italic=true})
  vim.api.nvim_set_hl(0, 'SpellBad', {fg='#e46258', undercurl=true})
  vim.api.nvim_set_hl(0, 'SpellCap', {fg='#e46258', undercurl=true})
  vim.api.nvim_set_hl(0, 'SpellLocal', {fg='#e46258', undercurl=true})
  vim.api.nvim_set_hl(0, 'SpellRare', {fg='#e46258', undercurl=true})
  vim.api.nvim_set_hl(0, 'Statement', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, 'StatusLine', {bg='#282828'})
  vim.api.nvim_set_hl(0, 'StatusLineNC', {bg='#282828'})
  vim.api.nvim_set_hl(0, 'StatusLineTerm', {bg='#282828'})
  vim.api.nvim_set_hl(0, 'StatusLineTermNC', {bg='#282828'})
  vim.api.nvim_set_hl(0, 'StderrMsg', {fg='#fb4c36'})
  vim.api.nvim_set_hl(0, 'StorageClass', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, 'String', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'Structure', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, 'Substitute', {fg='#ebdcb4', bg='#93455d'})
  vim.api.nvim_set_hl(0, 'TabLine', {fg='#818181', bg='#cfcfcf'})
  vim.api.nvim_set_hl(0, 'TabLineFill', {bg='#e8e8e8'})
  vim.api.nvim_set_hl(0, 'TabLineSel', {bold=true})
  vim.api.nvim_set_hl(0, 'Tag', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'TelescopeBorder', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'TelescopeMatching', {fg='#d2859a', bold=true})
  vim.api.nvim_set_hl(0, 'TelescopeSelection', {bg='#2e2e2e'})
  vim.api.nvim_set_hl(0, 'TelescopeSelectionCaret', {fg='#fb4c36', bg='#2e2e2e'})
  vim.api.nvim_set_hl(0, 'TermCursor', {fg='#282828', bg='#eee2c3'})
  vim.api.nvim_set_hl(0, 'TermCursorNC', {fg='#282828', bg='#998d6f'})
  vim.api.nvim_set_hl(0, 'Title', {fg='#ebdcb4', bold=true})
  vim.api.nvim_set_hl(0, 'Todo', {bold=true, underline=true})
  vim.api.nvim_set_hl(0, 'TroubleNormal', {fg='#ebdcb4'})
  vim.api.nvim_set_hl(0, 'TroubleSource', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'TroubleText', {fg='#ebdcb4'})
  vim.api.nvim_set_hl(0, 'Type', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, 'Typedef', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, 'Underlined', {underline=true})
  vim.api.nvim_set_hl(0, 'VertSplit', {fg='#6a6a6a'})
  vim.api.nvim_set_hl(0, 'Visual', {bg='#555041'})
  vim.api.nvim_set_hl(0, 'VisualNOS', {bg='#555041'})
  vim.api.nvim_set_hl(0, 'WarningMsg', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'WhichKey', {fg='#fb4c36', bold=true})
  vim.api.nvim_set_hl(0, 'WhichKeyGroup', {fg='#83a598'})
  vim.api.nvim_set_hl(0, 'WhichKeySeparator', {fg='#6a6a6a'})
  vim.api.nvim_set_hl(0, 'WhichKeyValue', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'Whitespace', {fg='#616161'})
  vim.api.nvim_set_hl(0, 'WildMenu', {fg='#282828', bg='#d2859a'})
  vim.api.nvim_set_hl(0, 'WinBar', {bg='#282828'})
  vim.api.nvim_set_hl(0, 'WinBarNC', {bg='#282828'})
  vim.api.nvim_set_hl(0, 'WinSeparator', {fg='#6a6a6a'})
  vim.api.nvim_set_hl(0, 'diffAdded', {bg='#3a3a25'})
  vim.api.nvim_set_hl(0, 'diffChanged', {bg='#273e35'})
  vim.api.nvim_set_hl(0, 'diffFile', {fg='#f9bd30', bold=true})
  vim.api.nvim_set_hl(0, 'diffIndexLine', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'diffLine', {fg='#d2859a', bold=true})
  vim.api.nvim_set_hl(0, 'diffNewFile', {fg='#b7ba26', italic=true})
  vim.api.nvim_set_hl(0, 'diffOldFile', {fg='#fb4c36', italic=true})
  vim.api.nvim_set_hl(0, 'diffRemoved', {bg='#52302e'})
  vim.api.nvim_set_hl(0, 'gitcommitOverflow', {fg='#f9bd30'})
  vim.api.nvim_set_hl(0, 'helpHyperTextEntry', {fg='#9e9e9e', bold=true})
  vim.api.nvim_set_hl(0, 'helpHyperTextJump', {fg='#c9ba94', underline=true})
  vim.api.nvim_set_hl(0, 'helpOption', {fg='#afa280', italic=true})
  vim.api.nvim_set_hl(0, 'helpSpecial', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, 'lCursor', {fg='#282828', bg='#998d6f'})
  vim.api.nvim_set_hl(0, 'markdownCode', {fg='#82c07b', italic=true})
  vim.api.nvim_set_hl(0, 'markdownLinkText', {fg='#c9ba94', underline=true})
  vim.api.nvim_set_hl(0, 'markdownLinkTextDelimiter', {fg='#848484'})
  vim.api.nvim_set_hl(0, 'markdownUrl', {fg='#727272'})
  vim.api.nvim_set_hl(0, 'nvim_set_hl_x_hi_clear_bugfix', {fg='#ff0000'})
end
